# Generated by Django 3.2.9 on 2021-12-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(null=True, unique=True),
        ),
    ]
