# Generated by Django 3.2.9 on 2021-11-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.user'),
        ),
    ]
