# Generated by Django 3.2.9 on 2021-12-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_alter_booking_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
    ]
