# Generated by Django 3.2.9 on 2021-11-30 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_alter_receptionist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(unique=True)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('next_of_kin_fullname', models.CharField(max_length=100)),
                ('next_of_kin_phone_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.customer')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_no', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('single_room_img', models.TextField(null=True)),
                ('single_room_img2', models.TextField(null=True)),
                ('img_url', models.TextField(null=True)),
                ('price', models.CharField(max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Delux Room', 'Delux Room'), ('Family Room', 'Family Room'), ('Suite Room', 'Suite Room'), ('Classic Room', 'Classic Room'), ('Superior Room', 'Superior Room'), ('Luxury Room', 'Luxury Room')], max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='avartar_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='gender',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.roomstatus'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.roomtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.receptionist'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.paymenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.paymenttype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.receptionist'),
        ),
    ]
