# Generated by Django 3.2.9 on 2021-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_auto_20211205_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avataruser.png', null=True, upload_to=''),
        ),
    ]
