# Generated by Django 3.2.9 on 2021-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_auto_20211207_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
