# Generated by Django 3.2.9 on 2021-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_auto_20211130_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='avartar_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
