# Generated by Django 3.2.9 on 2021-12-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0011_auto_20211205_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='single_room_img',
        ),
        migrations.RemoveField(
            model_name='room',
            name='single_room_img2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('All Rooms', 'All Rooms'), ('Dorm Beds', 'Dorm Beds'), ('Private Room', 'Private Room'), ('Suites', 'Suites')], default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='room',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
