# Generated by Django 3.2.9 on 2021-12-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0012_auto_20211205_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
