# Generated by Django 3.2.9 on 2021-12-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0013_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.paymenttype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.roomstatus'),
        ),
    ]
