# Generated by Django 3.2.9 on 2021-12-06 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMS', '0014_auto_20211206_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='room_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomstatus',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HMS.room'),
        ),
        migrations.AddField(
            model_name='roomstatus',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.payment'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HMS.payment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.payment'),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
