# Generated by Django 3.2.9 on 2021-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0015_auto_20211206_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Expired', 'Expired')], default=0, max_length=20),
        ),
    ]
