# Generated by Django 3.2.9 on 2021-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0017_alter_roomstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
    ]
