# Generated by Django 3.2.9 on 2021-12-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0019_auto_20211207_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
